import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/_Navbar/Navbar";
import HeroSection from "./_components/_HeroSection";
import ServicesCategories from "./_components/_ServicesCategories";
import '@fortawesome/fontawesome-free/css/all.min.css';
import Footer from "./_components/_Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="ar">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        <HeroSection/>
        <ServicesCategories />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
